cleanup
Signed-off-by: muthuja <muthujabavaji.vempalli@progress.com>

diff --git a/3.3/windows/2019/Dockerfile b/3.3/windows/2019/Dockerfile
--- a/3.3/windows/2019/Dockerfile
+++ b/3.3/windows/2019/Dockerfile
@@ -1,29 +1,52 @@
+
 FROM mcr.microsoft.com/windows/servercore:ltsc2019
 
-ENV BUNDLE_SILENCE_ROOT_WARNING=true \
-    GIT_DISCOVERY_ACROSS_FILESYSTEM=true
+# Download base ruby
+RUN powershell \
+    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
+    Invoke-WebRequest https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-3.3.3-1/rubyinstaller-3.3.3-1-x64.exe -Outfile rubyinstaller.exe
+# Download Inno Setup    
+RUN powershell \
+    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
+    Invoke-WebRequest http://www.jrsoftware.org/download.php/is.exe -Outfile inno-setup.exe
 
-# When launched by user, default to PowerShell if no other command specified.
-CMD ["powershell.exe", "-NoLogo", "-ExecutionPolicy", "Bypass"]
-
-# Install 7zip
-RUN powershell -Command (New-Object System.Net.WebClient).DownloadFile('https://www.7-zip.org/a/7z2407-x64.exe', 'c:\7z2407-x64.exe'); \
-  Start-Process -FilePath 'c:\7z2407-x64.exe' -Args "/S" -Verb RunAs -Wait ; \
-  [Environment]::SetEnvironmentVariable('PATH', $env:PATH + ';C:\Program Files\7-Zip', [EnvironmentVariableTarget]::Machine); \
-  Remove-Item 'C:\7z2407-x64.exe'
-
-# Download Ruby archive, extract it and add the "bin" folder to the PATH variable
-RUN powershell -Command (New-Object System.Net.WebClient).DownloadFile('https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-3.3.3-1/rubyinstaller-3.3.3-1-x64.7z', 'C:\rubyinstaller-3.3.3-1-x64.7z'); \
-  7z x -o'C:\' rubyinstaller-3.3.3-1-x64.7z -r ; \
-  [Environment]::SetEnvironmentVariable('PATH', $env:PATH + ';C:\rubyinstaller-3.3.3-1-x64\bin', [EnvironmentVariableTarget]::Machine); \
-  Remove-Item 'C:\rubyinstaller-3.3.3-1-x64.7z'
-
-# Download MSYS2 dev kit, extract it and add to the PATH variable
-
-RUN powershell -Command (New-Object System.Net.WebClient).DownloadFile('https://github.com/msys2/msys2-installer/releases/download/2024-05-07/msys2-x86_64-20240507.exe', 'c:\\msys2-x86_64-20240507.exe'); \
-   .\msys2-x86_64-20240507.exe in --confirm-command --accept-messages --root C:\msys2 ; \
-   [Environment]::SetEnvironmentVariable('PATH', $env:PATH + ';C:\msys2', [EnvironmentVariableTarget]::Machine); \
-   Remove-Item 'C:\msys2-x86_64-20240507.exe'
-
+# Install Inno Setup
+RUN cmd /c inno-setup.exe /verysilent /allusers
+RUN powershell [Environment]::SetEnvironmentVariable('PATH', $env:PATH + ';c:/Program Files (x86)/Inno Setup 6', 'Machine')
+RUN iscc --version || (exit 0)
+    
+# Install base ruby and initialize Devkit
+RUN powershell -Command Start-Process c:\rubyinstaller.exe -ArgumentList '/verysilent /allusers /dir=C:\\ruby33' -Wait
+RUN powershell $env:PATH = [Environment]::GetEnvironmentVariable('PATH','Machine'); \
+    $env:RUBYOPT = [Environment]::GetEnvironmentVariable('RUBYOPT','Machine')
 RUN ruby --version
-RUN bundler --version   
+#RUN ridk install 1
+
+# Download git
+RUN powershell \
+    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
+    Invoke-WebRequest https://github.com/git-for-windows/git/releases/download/v2.45.2.windows.1/Git-2.45.2-32-bit.exe  -Outfile git-installer.exe
+
+# Install git
+RUN powershell -Command Start-Process c:\ git-installer.exe '/verysilent' -Wait
+RUN git --version
+
+
+RUN ridk enable
+
+# pacman fails with EXDEV error after download when /var/cache/pkg is bind mounted into the container.
+# Therefore mount /var/cache directory an let pacman create the pkg directory.
+RUN ridk exec rm -r c:/ruby24-x64/msys64/var/cache/pacman/pkg
+
+# Import the git repository and unpack it in /build
+WORKDIR /build
+COPY gitrepo .git/
+RUN dir
+RUN git checkout -f
+
+# Install required rubygems
+RUN gem install bundler --no-doc
+RUN bundle
+
+WORKDIR /build/docker
+CMD rake
